#!/bin/bash

# text gambar
apt-get install boxes

# color text
cd
rm -rf /root/.bashrc
wget -O /root/.bashrc "https://github.com/SSL3/OrangSabahan007/raw/master/.bashrc"

# install lolcat
sudo apt-get -y install ruby
sudo gem install lolcat

# download script
cd
wget -O /usr/bin/motd "https://github.com/SSL3/OrangSabahan007/raw/master/motd"
wget -O /usr/bin/benchmark "https://github.com/SSL3/OrangSabahan007/raw/master/benchmark.sh"
wget -O /usr/bin/speedtest "https://github.com/SSL3/OrangSabahan007/raw/master/speedtest_cli.py"
wget -O /usr/bin/ps-mem "https://github.com/SSL3/OrangSabahan007/raw/master/ps_mem.py"
wget -O /usr/bin/dropmon "https://github.com/SSL3/OrangSabahan007/raw/master/dropmon.sh"
wget -O /usr/bin/menu "https://github.com/SSL3/OrangSabahan007/raw/master/menu.sh"
wget -O /usr/bin/user-active-list "https://github.com/SSL3/OrangSabahan007/raw/master/user-active-list.sh"
wget -O /usr/bin/user-add "https://github.com/SSL3/OrangSabahan007/raw/master/user-add.sh"
wget -O /usr/bin/user-add-pptp "https://raw.githubusercontent.com/sslmode/sslmode/master/tools/user-add-pptp.sh"
wget -O /usr/bin/user-del "https://github.com/SSL3/OrangSabahan007/raw/master/user-del.sh"
wget -O /usr/bin/disable-user-expire "https://github.com/SSL3/OrangSabahan007/raw/master/disable-user-expire.sh"
wget -O /usr/bin/delete-user-expire "https://github.com/SSL3/OrangSabahan007/raw/master/delete-user-expire.sh"
wget -O /usr/bin/banned-user "https://github.com/SSL3/OrangSabahan007/raw/master/banned-user.sh"
wget -O /usr/bin/unbanned-user "https://github.com/SSL3/OrangSabahan007/raw/master/unbanned-user.sh"
wget -O /usr/bin/user-expire-list "https://github.com/SSL3/OrangSabahan007/raw/master/user-expire-list.sh"
wget -O /usr/bin/user-gen "https://raw.githubusercontent.com/sslmode/sslmode/master/tools/user-gen.sh"
wget -O /usr/bin/userlimit.sh "https://github.com/SSL3/OrangSabahan007/raw/master/userlimit.sh"
wget -O /usr/bin/userlimitssh.sh "https://github.com/SSL3/OrangSabahan007/raw/master/userlimitssh.sh"
wget -O /usr/bin/user-list "https://github.com/SSL3/OrangSabahan007/raw/master/user-list.sh"
wget -O /usr/bin/user-login "https://github.com/SSL3/OrangSabahan007/raw/master/user-login.sh"
wget -O /usr/bin/user-pass "https://github.com/SSL3/OrangSabahan007/raw/master/user-pass.sh"
wget -O /usr/bin/user-renew "https://github.com/SSL3/OrangSabahan007/raw/master/user-renew.sh"
wget -O /usr/bin/clearcache.sh "https://github.com/SSL3/OrangSabahan007/raw/master/clearcache.sh"
wget -O /usr/bin/bannermenu "https://github.com/SSL3/OrangSabahan007/raw/master/bannermenu"
cd

#rm -rf /etc/cron.weekly/
#rm -rf /etc/cron.hourly/
#rm -rf /etc/cron.monthly/
rm -rf /etc/cron.daily/
wget -O /root/passwd "https://github.com/SSL3/OrangSabahan007/raw/master/passwd.sh"
chmod +x /root/passwd
echo "01 23 * * * root /root/passwd" > /etc/cron.d/passwd

echo "*/30 * * * * root service dropbear restart" > /etc/cron.d/dropbear
echo "00 23 * * * root /usr/bin/disable-user-expire" > /etc/cron.d/disable-user-expire
echo "0 */12 * * * root /sbin/reboot" > /etc/cron.d/reboot
#echo "00 01 * * * root echo 3 > /proc/sys/vm/drop_caches && swapoff -a && swapon -a" > /etc/cron.d/clearcacheram3swap
echo "*/30 * * * * root /usr/bin/clearcache.sh" > /etc/cron.d/clearcache1

cd
chmod +x /usr/bin/motd
chmod +x /usr/bin/benchmark
chmod +x /usr/bin/speedtest
chmod +x /usr/bin/ps-mem
#chmod +x /usr/bin/autokill
chmod +x /usr/bin/dropmon
chmod +x /usr/bin/menu
chmod +x /usr/bin/user-active-list
chmod +x /usr/bin/user-add
chmod +x /usr/bin/user-add-pptp
chmod +x /usr/bin/user-del
chmod +x /usr/bin/disable-user-expire
chmod +x /usr/bin/delete-user-expire
chmod +x /usr/bin/banned-user
chmod +x /usr/bin/unbanned-user
chmod +x /usr/bin/user-expire-list
chmod +x /usr/bin/user-gen
chmod +x /usr/bin/userlimit.sh
chmod +x /usr/bin/userlimitssh.sh
chmod +x /usr/bin/user-list
chmod +x /usr/bin/user-login
chmod +x /usr/bin/user-pass
chmod +x /usr/bin/user-renew
chmod +x /usr/bin/clearcache.sh
chmod +x /usr/bin/bannermenu
cd
